version: '3'

services:

#setup backend

  server:
    build: ./backend
    ports: 
        - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    environment:
        - NODE_ENV=development
    volumes:
        - ./backend:/app

#setup frontend

  frontend:
    build: ./frontend
    ports: 
        - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    environment:
        - REACT_APP_BACKEND_PORT=3001 
        - NODE_ENV=development
    volumes:
        - ./frontend:/app
